products_list = [
    "Antirock Sway Bars - Bolt-In Antirock Kits",
    "Antirock Sway Bars - Universal Antirock Kits",
    "Antirock Sway Bars - Pre-Runner Antirock Kit",
    "Antirock Sway Bars - Parts & Components",
    "Currectlync Steering System - JL (18-Up Jeep Wrangler)",
    "Currectlync Steering System - JT (20-Up Jeep Gladiator)",
    "Currectlync Steering System - JK (07-18 Jeep Wrangler)",
    "Currectlync Steering System - TJ/LJ (97-06 Jeep Wrangler)",
    "Currectlync Steering System - XJ (84-01 Jeep Cherokee)",
    "Currectlync Steering System - MJ (86-92 Jeep Comanche)",
    "Currectlync Steering System - ZJ (93-98 Jeep Cherokee)",
    "Currectlync Steering System - High Steer Knuckle Kits",
    "Currectlync Steering System - Universal Modular Extreme Duty",
    "Currectlync Steering System - Stabilizer Shocks & Brackets",
    "Currectlync Steering System - Ram Assist Components",
    "Currectlync Steering System - Replacement Parts",
    "Johnny Joint Rod Ends - Complete Joints",
    "Johnny Joint Rod Ends - Shop by Vehicle",
    "Johnny Joint Rod Ends - RockNuts, Bungs & Jam Nuts",
    "Johnny Joint Rod Ends - Tools",
    "Johnny Joint Rod Ends - Rebuild Kits",
    "Johnny Joint Rod Ends - Grease",
    "Johnny Joint Rod Ends - Parts Department",
    "RockNuts - RockNut Control Arms",
    "RockNuts - RockNut Kits",
    "RockNuts - RockNut Nuts",
    "RockNuts - RockNut Bungs",
    "Spare Tire Delete Panels - JL (18-up Jeep Wrangler)",
    "Spare Tire Delete Panels - JK (07-18 Jeep Wrangler)",
    "Suspension Kits - JL (18-Up Jeep Wrangler)",
    "Suspension Kits - JT (20-Up Jeep Gladiator)",
    "Suspension Kits - JK (07-18 Jeep Wrangler)",
    "Suspension Kits - TJ/LJ (97-06 Jeep Wrangler)",
    "Suspension Kits - XJ (84-01 Jeep Cherokee)",
    "Towing Solutions - JL (18-Up Jeep Wrangler)",
    "Towing Solutions - JT (20-Up Jeep Gladiator)",
    "Towing Solutions - JK (07-18 Jeep Wrangler)",
    "Towing Solutions - TJ/LJ (97-06 Jeep Wrangler)",
    "Towing Solutions - YJ (87-95 Jeep Wrangler)",
    "Towing Solutions - CJ (82-86 Jeep)",
    "Towing Solutions - Tow Bars & Accessories",
    "John Currie Performance Group - Currectrac Control Arms",
    "John Currie Performance Group - Antirock Sway Bar Kits",
    "John Currie Performance Group - Johnny Joint Rod Ends",
    "John Currie Performance Group - RockNuts, Bungs & Jam Nuts",
    "New Products",
    "Accessories & Swag - EZ Deflators",
    "Accessories & Swag - Frame Plugs",
    "Accessories & Swag - ProCal Module",
    "Accessories & Swag - T-Shirts",
    "Accessories & Swag - Sweat Shirts",
    "Accessories & Swag - Women's Apparel",
    "Accessories & Swag - Headwear",
    "Accessories & Swag - Socks",
    "Accessories & Swag - Bag",
    "Accessories & Swag - Cornhole Set",
    "Accessories & Swag - License Plate Frame",
    "Accessories & Swag - Shop Banner",
    "Accessories & Swag - Stickers",
    "Parts Department - Adjusters",
    "Parts Department - Bearings (Spherical)",
    "Parts Department - Bolts",
    "Parts Department - Boots",
    "Parts Department - Brackets",
    "Parts Department - Brake Hoses",
    "Parts Department - Bump Stops",
    "Parts Department - Bushings",
    "Parts Department - Clamps",
    "Parts Department - Cotter Pins",
    "Parts Department - Currectrac Control Arms",
    "Parts Department - Frame Plugs",
    "Parts Department - Geometry Correction Brackets",
    "Parts Department - Grease",
    "Parts Department - Grommets",
    "Parts Department - Hardware Packs",
    "Parts Department - Johnny Joint Housing Kits",
    "Parts Department - Misc. Suspension",
    "Parts Department - Nuts",
    "Parts Department - O-Rings",
    "Parts Department - Pitman Arms",
    "Parts Department - Screws",
    "Parts Department - Shackle Plates",
    "Parts Department - Shims",
    "Parts Department - Shocks",
    "Parts Department - Skid Plates",
    "Parts Department - Sleeves",
    "Parts Department - Snap Rings",
    "Parts Department - Spacers",
    "Parts Department - Spring Plates",
    "Parts Department - Springs",
    "Parts Department - Steering",
    "Parts Department - Studs",
    "Parts Department - Sway Bar End Link Ends",
    "Parts Department - Sway Bar End Link Rods",
    "Parts Department - Sway Bar End Link Sets",
    "Parts Department - Tabs",
    "Parts Department - Thread Locker",
    "Parts Department - Threaded Bungs",
    "Parts Department - Tools",
    "Parts Department - Towing Hardware",
    "Parts Department - Trac Bars & Parts",
    "Parts Department - Tubes",
    "Parts Department - Uni-Ball",
    "Parts Department - Washers",
    "Parts Department - Zerk Fittings"
]